export const getWatermarkHtml = (profileOrRole?: any) => {
  let tier = 'Free';
  let role = 'siswa';
  if (typeof profileOrRole === 'string') {
    tier = profileOrRole;
  } else if (profileOrRole) {
    tier = profileOrRole.tier || 'Free';
    role = profileOrRole.role || 'siswa';
  }
  
  tier = tier.toLowerCase();
  role = role.toLowerCase();
  
  const isPrivileged = tier === 'titan' || role === 'owner' || role === 'admin';
  if (isPrivileged || (tier !== 'free' && tier !== 'guest')) {
    return '';
  }
  return `
    <style>
      .watermark {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-45deg);
        font-size: 80px;
        color: rgba(200, 200, 200, 0.2);
        z-index: 9999;
        pointer-events: none;
        white-space: nowrap;
        user-select: none;
        -webkit-user-select: none;
      }
      @media print {
        .watermark {
          color: rgba(150, 150, 150, 0.15) !important;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
      }
    </style>
    <div class="watermark">Generated by Pemuryadi</div>
  `;
};

export const getSignatureHtml = (profile: any) => {
  if (!profile || (!profile.kepalaSekolah && !profile.nama && !profile.displayName)) return '';
  
  const today = new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
  
  return `
    <div style="margin-top: 40px; display: flex; justify-content: space-between; text-align: center; font-size: 12px; page-break-inside: avoid;">
        <div style="width: 45%;">
            <p>Mengetahui,</p>
            <p>Kepala Sekolah</p>
            <br><br><br><br>
            <p style="font-weight: bold; text-decoration: underline;">${profile.kepalaSekolah || '................................'}</p>
            <p>${profile.jenisNipKepalaSekolah || 'NIP'}. ${profile.nipKepalaSekolah || '................................'}</p>
        </div>
        <div style="width: 45%;">
            <p>Dibuat pada, ${today}</p>
            <p>Guru Pengampu</p>
            <br><br><br><br>
            <p style="font-weight: bold; text-decoration: underline;">${profile.nama || profile.displayName || '................................'}</p>
            <p>${profile.jenisNipGuru || 'NIP'}. ${profile.nip || '................................'}</p>
        </div>
    </div>
  `;
};

export const universalPrint = (contentHtml: string, title: string = 'Print Document', additionalStyles: string = '') => {
  const container = document.createElement('div');
  container.id = 'universal-print-container';
  
  const style = document.createElement('style');
  style.textContent = `
    @media print {
      body > *:not(#universal-print-container) {
        display: none !important;
      }
      #universal-print-container {
        display: block !important;
        position: relative;
        width: 100%;
        background: white;
        color: black;
      }
      @page {
        size: A4;
        margin: 20mm;
      }
      body {
        background: #fff !important;
        margin: 0 !important;
        padding: 0 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
      table { width: 100%; border-collapse: collapse; page-break-inside: auto; margin-bottom: 20px; }
      tr { page-break-inside: avoid; page-break-after: auto; }
      th, td { border: 1px solid black; padding: 8px; text-align: left; }
      th { background-color: #f2f2f2 !important; }
      .text-center { text-align: center; }
      .font-bold { font-weight: bold; }
      .mb-4 { margin-bottom: 1rem; }
      .mt-8 { margin-top: 2rem; }
      .flex { display: flex; }
      .justify-between { justify-content: space-between; }
      .justify-end { justify-content: flex-end; }
      ${additionalStyles}
    }
    @media screen {
      #universal-print-container {
        display: none !important;
      }
    }
  `;
  
  // Extract global styles to keep Tailwind and Font working
  const globalStyles = Array.from(document.querySelectorAll('style, link[rel="stylesheet"]'))
    .map(el => el.outerHTML)
    .join('\n');

  container.innerHTML = `
    ${globalStyles}
    <div style="font-family: 'Times New Roman', Times, serif; padding: 0; color: black; line-height: 1.5;">
      ${contentHtml}
    </div>
  `;
  container.appendChild(style);
  document.body.appendChild(container);
  
  const originalTitle = document.title;
  document.title = title;
  
  const cleanup = () => {
    if (document.body.contains(container)) {
      document.body.removeChild(container);
    }
    document.title = originalTitle;
    window.removeEventListener('afterprint', cleanup);
  };
  
  window.addEventListener('afterprint', cleanup);
  
  // Also clean up if afterprint doesn't fire (some mobile browsers)
  setTimeout(() => {
    if (document.body.contains(container)) {
      document.body.removeChild(container);
      document.title = originalTitle;
    }
  }, 300000); // 5 minutes fallback
  
  window.print();
};

export const printElement = (elementId: string, title: string, profile: any) => {
  const printContent = document.getElementById(elementId);
  if (!printContent) return;

  // Open all details before getting HTML so they print expanded
  const detailsElements = printContent.querySelectorAll('details');
  detailsElements.forEach(d => d.setAttribute('open', 'true'));
  
  const watermark = getWatermarkHtml(profile?.role || profile);
  const signature = getSignatureHtml(profile);
  
  universalPrint(`
    ${watermark}
    <div style="position: relative; z-index: 1;">
      ${printContent.innerHTML}
      ${signature}
    </div>
  `, `Print - ${title}`, `
    .print-section {
      border: 1.5px solid #000 !important;
      padding: 15px !important;
      margin-bottom: 5mm !important;
      page-break-after: auto;
      page-break-inside: auto;
      -webkit-box-decoration-break: clone !important;
      box-decoration-break: clone !important;
      box-sizing: border-box;
      position: relative;
      background: #fff !important;
      box-shadow: none !important;
    }
    .print-section p, .print-section li {
      page-break-inside: avoid;
    }
    .page-break {
      page-break-before: always;
    }
    .no-print { display: none !important; }
  `);
};


export const createPrintWindow = () => {
  let htmlContent = '';
  return {
    document: {
      write: (html: string) => { htmlContent += html; },
      close: () => {
        try {
          // Extract body content
          const bodyMatch = htmlContent.match(/<body[^>]*>([\s\S]*)<\/body>/i);
          let bodyHtml = bodyMatch ? bodyMatch[1] : htmlContent;
          
          // Remove script tags to prevent them from executing
          bodyHtml = bodyHtml.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');

          // Extract styles
          const styleMatch = htmlContent.match(/<style[^>]*>([\s\S]*?)<\/style>/gi);
          const styles = styleMatch ? styleMatch.map(s => s.replace(/<\/?style[^>]*>/gi, '')).join('\n') : '';
          
          // Extract title
          const titleMatch = htmlContent.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
          const title = titleMatch ? titleMatch[1] : 'Print Document';

          universalPrint(bodyHtml, title, styles);
        } catch (err: any) {
          console.error("Print extraction error:", err);
          alert("Terjadi kesalahan saat memproses dokumen untuk dicetak: " + err.message);
        }
      }
    },
    print: () => {},
    focus: () => {}
  } as any;
};
